import { Product } from "../types/db";

export const MOCK_PRODUCTS: Product[] = [
  // --- Espresso-Based ---
  {
    id: "1",
    category: "Espresso-Based",
    name: "Americano",
    price: 80,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    category: "Espresso-Based",
    name: "Café Latte",
    price: 100,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    category: "Espresso-Based",
    name: "Cappuccino",
    price: 100,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    category: "Espresso-Based",
    name: "Mocha",
    price: 130,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    category: "Espresso-Based",
    name: "White Chocolate Mocha",
    price: 130,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    category: "Espresso-Based",
    name: "Caramel Macchiatto",
    price: 140,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },
  {
    id: "7",
    category: "Espresso-Based",
    name: "Spanish Latte",
    price: 120,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },
  {
    id: "8",
    category: "Espresso-Based",
    name: "Vietnamese Latte",
    price: 120,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },

  // --- Special Drinks ---
  {
    id: "9",
    category: "Special Drinks",
    name: "Iced Triple Kick",
    price: 150,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },
  {
    id: "10",
    category: "Special Drinks",
    name: "Iced Sea Salt Latte",
    price: 130,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },

  // --- Non-Espresso ---
  {
    id: "11",
    category: "Non-Espresso",
    name: "Iced Matcha Latte",
    price: 130,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },
  {
    id: "12",
    category: "Non-Espresso",
    name: "Iced Chocolate",
    price: 130,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },
  {
    id: "13",
    category: "Non-Espresso",
    name: "Still Iced Tea",
    price: 110,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },

  // --- Coffee-Based Frappe ---
  {
    id: "14",
    category: "Coffee-Based Frappe",
    name: "Java Chip",
    price: 135,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },
  {
    id: "15",
    category: "Coffee-Based Frappe",
    name: "Coffee Jelly",
    price: 135,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },
  {
    id: "16",
    category: "Coffee-Based Frappe",
    name: "Caramel Frappe",
    price: 120,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },

  // --- Non-Coffee Frappe ---
  {
    id: "17",
    category: "Non-Coffee Frappe",
    name: "Oreo",
    price: 130,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },
  {
    id: "18",
    category: "Non-Coffee Frappe",
    name: "Chocolate",
    price: 130,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },
  {
    id: "19",
    category: "Non-Coffee Frappe",
    name: "Strawberries & Cream",
    price: 140,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },
  {
    id: "20",
    category: "Non-Coffee Frappe",
    name: "Mangoes & Cream",
    price: 120,
    stock_qty: 50,
    created_at: new Date().toISOString(),
  },

  // --- Pasta ---
  {
    id: "21",
    category: "Pasta",
    name: "Bolognese",
    price: 135,
    stock_qty: 30,
    created_at: new Date().toISOString(),
  },
  {
    id: "22",
    category: "Pasta",
    name: "Creamy Carbonara",
    price: 135,
    stock_qty: 30,
    created_at: new Date().toISOString(),
  },

  // --- Rice Meals ---
  {
    id: "23",
    category: "Rice Meals",
    name: "Hungarian Sausage",
    price: 110,
    stock_qty: 30,
    created_at: new Date().toISOString(),
  },
  {
    id: "24",
    category: "Rice Meals",
    name: "Crispy Liempo",
    price: 135,
    stock_qty: 30,
    created_at: new Date().toISOString(),
  },

  // --- Snacks ---
  {
    id: "25",
    category: "Snacks",
    name: "French Fries",
    price: 100,
    stock_qty: 40,
    created_at: new Date().toISOString(),
  },
  {
    id: "26",
    category: "Snacks",
    name: "Cheese Sticks",
    price: 80,
    stock_qty: 40,
    created_at: new Date().toISOString(),
  },
  {
    id: "27",
    category: "Snacks",
    name: "Cheese Quesadilla",
    price: 115,
    stock_qty: 40,
    created_at: new Date().toISOString(),
  },
  {
    id: "28",
    category: "Snacks",
    name: "Nacho-Nachos",
    price: 150,
    stock_qty: 40,
    created_at: new Date().toISOString(),
  },
  {
    id: "29",
    category: "Snacks",
    name: "Chicken Wings",
    price: 110,
    stock_qty: 40,
    created_at: new Date().toISOString(),
  },
];
